// Copyright 2025, University of Colorado Boulder

/**
 * Module that includes all Alpenglow dependencies, so that requiring this module will return an object
 * that consists of the entire exported 'alpenglow' namespace API.
 *
 * The API is actually generated by the 'alpenglow' module, so if this module (or all other modules) are
 * not included, the 'alpenglow' namespace may not be complete.
 *
 * @author Jonathan Olson (PhET Interactive Simulations)
 */


import './alpenglow.js';

import './webgpu/compute/u32.js';
import './webgpu/compute/u32Hex.js';
import './webgpu/compute/i32.js';
import './webgpu/compute/i32Hex.js';
import './webgpu/compute/f32.js';
import './webgpu/compute/decimal.js';

import './render-program/PolygonFilterType.js';
import './render-program/Mesh.js';
import './render-program/RenderBlendType.js';
import './render-program/RenderComposeType.js';
import './render-program/RenderExtend.js';
import './render-program/RenderProgramNeeds.js';
import './render-program/RenderEvaluationContext.js';
import './render-program/RenderExecutionStack.js';
import './render-program/RenderExecutor.js';
import './render-program/RenderInstruction.js';
import './render-program/RenderProgram.js';
import './render-program/RenderColorSpaceConversion.js';
import './render-program/RenderProgram.js';
import './render-program/RenderPath.js';
import './render-program/RenderPathBoolean.js';
import './render-program/RenderColor.js';
import './render-program/RenderColorSpace.js';
import './render-program/RenderColorSpaceConversion.js';
import './render-program/RenderAlpha.js';
import './render-program/RenderNormalize.js';
import './render-program/RenderPremultiply.js';
import './render-program/RenderUnpremultiply.js';
import './render-program/RenderSRGBToLinearSRGB.js';
import './render-program/RenderLinearSRGBToSRGB.js';
import './render-program/RenderOklabToLinearSRGB.js';
import './render-program/RenderLinearSRGBToOklab.js';
import './render-program/RenderLinearDisplayP3ToLinearSRGB.js';
import './render-program/RenderLinearSRGBToLinearDisplayP3.js';
import './render-program/RenderBlendCompose.js';
import './render-program/RenderStack.js';
import './render-program/RenderPlanar.js';
import './render-program/RenderDepthSort.js';
import './render-program/RenderLight.js';
import './render-program/RenderNormalDebug.js';
import './render-program/RenderPhong.js';
import './render-program/RenderFilter.js';
import './render-program/RenderGradientStop.js';
import './render-program/RenderLinearRange.js';
import './render-program/RenderImage.js';
import './render-program/RenderImageable.js';
import './render-program/RenderLinearBlend.js';
import './render-program/RenderBarycentricBlend.js';
import './render-program/RenderBarycentricPerspectiveBlend.js';
import './render-program/RenderLinearGradient.js';
import './render-program/RenderRadialBlend.js';
import './render-program/RenderRadialGradient.js';
import './render-program/RenderResampleType.js';
import './render-program/FillRule.js';
import './render-program/RenderTrail.js';
import './render-program/RenderPathReplacer.js';
import './render-program/RenderFromNode.js';

import './cag/LinearEdge.js';

import './cag/BigIntVector2.js';
import './cag/BigRational.js';
import './cag/BigRationalVector2.js';
import './cag/BoundsIntersectionFilter.js';
import './cag/HilbertMapping.js';

import './clip/ClipSimplifier.js';

import './cag/ClippableFace.js';
import './cag/BoundedSubpath.js';

import './cag/IntegerEdge.js';
import './cag/IntersectionPoint.js';
import './cag/LineIntersector.js';
import './cag/LineSplitter.js';
import './cag/RationalBoundary.js';
import './cag/RationalFace.js';
import './cag/RationalHalfEdge.js';
import './cag/RationalIntersection.js';
import './cag/WindingMap.js';
import './cag/PolygonalBoolean.js';

import './clip/CohenSutherlandClipping.js';
import './clip/LineClipping.js';
import './clip/BoundsClipping.js';
import './clip/StripeClipping.js';
import './clip/GridClipping.js';

import './cag/FaceConversion.js';

import './raster/RasterColorConverter.js';
import './raster/RasterPremultipliedConverter.js';
import './raster/CombinedRaster.js';
import './raster/OutputRaster.js';
import './raster/PolygonBilinear.js';
import './raster/PolygonMitchellNetravali.js';
import './raster/RenderableFace.js';
import './raster/Rasterize.js';
import './raster/VectorCanvas.js';
import './raster/RasterLog.js';

import './parallel/ParallelContext.js';
import './parallel/ParallelKernel.js';
import './parallel/ParallelWorkgroup.js';
import './parallel/ParallelExecutor.js';
import './parallel/ParallelStorageArray.js';
import './parallel/ParallelWorkgroupArray.js';
import './parallel/ParallelUtils.js';

import './parallel/raster-clip/RasterChunk.js';
import './parallel/raster-clip/RasterChunkReduceData.js';
import './parallel/raster-clip/RasterChunkReducePair.js';
import './parallel/raster-clip/RasterChunkReduceQuad.js';
import './parallel/raster-clip/RasterCompleteChunk.js';
import './parallel/raster-clip/RasterEdge.js';
import './parallel/raster-clip/RasterEdgeClip.js';
import './parallel/raster-clip/RasterCompleteEdge.js';
import './parallel/raster-clip/RasterClippedChunk.js';
import './parallel/raster-clip/RasterSplitReduceData.js';
import './parallel/raster-clip/ParallelRasterInitialChunk.js';
import './parallel/raster-clip/ParallelRasterInitialClip.js';
import './parallel/raster-clip/ParallelRasterChunkReduce.js';
import './parallel/raster-clip/ParallelRasterInitialEdgeReduce.js';
import './parallel/raster-clip/ParallelRasterSplitReduce.js';
import './parallel/raster-clip/ParallelRasterEdgeScan.js';
import './parallel/raster-clip/ParallelRasterInitialSplitReduce.js';
import './parallel/raster-clip/ParallelRasterSplitScan.js';
import './parallel/raster-clip/ParallelRasterChunkIndexPatch.js';
import './parallel/raster-clip/ParallelRasterEdgeIndexPatch.js';
import './parallel/raster-clip/ParallelRaster.js';

import './webgpu/wgsl/WGSLString.js';

import './webgpu/WebGPURecorder.js';
import './webgpu/WebGPUAPI.js';
import './webgpu/compute/DeviceContext.js';
import './webgpu/BlitShader.js';
import './webgpu/compute/ByteEncoder.js';
import './webgpu/compute/ConcreteType.js';
import './webgpu/compute/ConsoleLogger.js';
import './webgpu/compute/BufferLogger.js';
import './webgpu/compute/TimestampLogger.js';
import './webgpu/compute/TypedBuffer.js';
import './webgpu/compute/BindingLocation.js';

import './webgpu/compute/BindingType.js';
import './webgpu/compute/BufferBindingType.js';
import './webgpu/compute/StorageTextureBindingType.js';
import './webgpu/compute/TextureBindingType.js';
import './webgpu/compute/ConcreteBindingType.js';
import './webgpu/compute/ResourceSlot.js';
import './webgpu/compute/BufferSlotSlice.js';
import './webgpu/compute/BufferSlot.js';
import './webgpu/compute/BufferArraySlot.js';
import './webgpu/compute/TextureViewSlot.js';
import './webgpu/compute/Resource.js';
import './webgpu/compute/BufferResource.js';
import './webgpu/compute/TextureViewResource.js';
import './webgpu/compute/ResourceUsage.js';
import './webgpu/compute/BindingDescriptor.js';
import './webgpu/compute/Binding.js';
import './webgpu/compute/BufferBinding.js';
import './webgpu/compute/BindGroupLayout.js';
import './webgpu/compute/PipelineLayout.js';
import './webgpu/compute/PipelineBlueprint.js';
import './webgpu/compute/Module.js';
import './webgpu/compute/DirectModule.js';
import './webgpu/compute/IndirectModule.js';
import './webgpu/compute/CompositeModule.js';
import './webgpu/compute/Routine.js';
import './webgpu/compute/Procedure.js';
import './webgpu/compute/BindGroup.js';
import './webgpu/compute/ComputePipeline.js';
import './webgpu/compute/ComputePass.js';
import './webgpu/compute/ExecutionContext.js';
import './webgpu/compute/Executor.js';

import './webgpu/wgsl/WGSLUtils.js';

import './webgpu/wgsl/gpu/binaryExpressionStatementWGSL.js';
import './webgpu/wgsl/gpu/coalescedLoopWGSL.js';
import './webgpu/wgsl/gpu/commentWGSL.js';
import './webgpu/wgsl/gpu/conditionalIfWGSL.js';
import './webgpu/wgsl/gpu/fromStripedIndexWGSL.js';
import './webgpu/wgsl/gpu/getConvergentIndexWGSL.js';
import './webgpu/wgsl/gpu/loadMultipleWGSL.js';
import './webgpu/wgsl/gpu/loadReducedWGSL.js';
import './webgpu/wgsl/gpu/ifLogWGSL.js';
import './webgpu/wgsl/gpu/logWGSL.js';
import './webgpu/wgsl/gpu/logRakedWGSL.js';
import './webgpu/wgsl/gpu/logValueWGSL.js';
import './webgpu/wgsl/gpu/logStringWGSL.js';
import './webgpu/wgsl/gpu/mainLogBarrier.js';
import './webgpu/wgsl/gpu/mainReduceWGSL.js';
import './webgpu/wgsl/gpu/reduceWGSL.js';
import './webgpu/wgsl/gpu/scanWGSL.js';
import './webgpu/wgsl/gpu/scanRakedWGSL.js';
import './webgpu/wgsl/gpu/toStripedIndexWGSL.js';
import './webgpu/wgsl/gpu/unrollWGSL.js';
import './webgpu/wgsl/gpu/bitPackRadixAccessWGSL.js';
import './webgpu/wgsl/gpu/bitPackRadixExclusiveScanWGSL.js';
import './webgpu/wgsl/gpu/bitPackRadixIncrementWGSL.js';
import './webgpu/wgsl/gpu/ceilDivideWGSL.js';
import './webgpu/wgsl/gpu/ceilDivideConstantDivisorWGSL.js';
import './webgpu/wgsl/gpu/nBitCompactSingleSortWGSL.js';
import './webgpu/wgsl/gpu/compactSingleRadixSortWGSL.js';
import './webgpu/wgsl/gpu/getCorankWGSL.js';
import './webgpu/wgsl/gpu/histogramWGSL.js';
import './webgpu/wgsl/gpu/radixHistogramWGSL.js';
import './webgpu/wgsl/gpu/mainRadixHistogramWGSL.js';
import './webgpu/wgsl/gpu/mainRadixScatterWGSL.js';
import './webgpu/wgsl/gpu/mainReduceAtomicWGSL.js';
import './webgpu/wgsl/gpu/mainReduceNonCommutativeWGSL.js';
import './webgpu/wgsl/gpu/scanComprehensiveWGSL.js';
import './webgpu/wgsl/gpu/mergeSequentialWGSL.js';
import './webgpu/wgsl/gpu/mergeSimpleWGSL.js';
import './webgpu/wgsl/gpu/mergeWGSL.js';
import './webgpu/wgsl/gpu/mainScanWGSL.js';
import './webgpu/wgsl/gpu/mainMergeSimpleWGSL.js';
import './webgpu/wgsl/gpu/mainMergeWGSL.js';
import './webgpu/wgsl/gpu/mainHistogramWGSL.js';

// math
import './webgpu/wgsl/math/cbrtWGSL.js';
import './webgpu/wgsl/math/u64WGSL.js';
import './webgpu/wgsl/math/i64WGSL.js';
import './webgpu/wgsl/math/q128WGSL.js';
import './webgpu/wgsl/math/i32_to_i64WGSL.js';
import './webgpu/wgsl/math/ZERO_u64WGSL.js';
import './webgpu/wgsl/math/ONE_u64WGSL.js';
import './webgpu/wgsl/math/ZERO_q128WGSL.js';
import './webgpu/wgsl/math/ONE_q128WGSL.js';
import './webgpu/wgsl/math/u32_to_u64WGSL.js';
import './webgpu/wgsl/math/add_u32_u32_to_u64WGSL.js';
import './webgpu/wgsl/math/mul_u32_u32_to_u64WGSL.js';
import './webgpu/wgsl/math/add_u64_u64WGSL.js';
import './webgpu/wgsl/math/add_i64_i64WGSL.js';
import './webgpu/wgsl/math/negate_i64WGSL.js';
import './webgpu/wgsl/math/is_zero_u64WGSL.js';
import './webgpu/wgsl/math/is_negative_i64WGSL.js';
import './webgpu/wgsl/math/abs_i64WGSL.js';
import './webgpu/wgsl/math/left_shift_u64WGSL.js';
import './webgpu/wgsl/math/right_shift_u64WGSL.js';
import './webgpu/wgsl/math/first_leading_bit_u64WGSL.js';
import './webgpu/wgsl/math/first_trailing_bit_u64WGSL.js';
import './webgpu/wgsl/math/subtract_i64_i64WGSL.js';
import './webgpu/wgsl/math/cmp_u64_u64WGSL.js';
import './webgpu/wgsl/math/cmp_i64_i64WGSL.js';
import './webgpu/wgsl/math/mul_u64_u64WGSL.js';
import './webgpu/wgsl/math/mul_i64_i64WGSL.js';
import './webgpu/wgsl/math/div_u64_u64WGSL.js';
import './webgpu/wgsl/math/gcd_u64_u64WGSL.js';
import './webgpu/wgsl/math/i64_to_q128WGSL.js';
import './webgpu/wgsl/math/whole_i64_to_q128WGSL.js';
import './webgpu/wgsl/math/equals_cross_mul_q128WGSL.js';
import './webgpu/wgsl/math/is_zero_q128WGSL.js';
import './webgpu/wgsl/math/ratio_test_q128WGSL.js';
import './webgpu/wgsl/math/reduce_q128WGSL.js';
import './webgpu/wgsl/math/IntersectionPointWGSL.js';
import './webgpu/wgsl/math/LineSegmentIntersectionWGSL.js';
import './webgpu/wgsl/math/intersect_line_segmentsWGSL.js';

// color
import './webgpu/wgsl/color/premultiplyWGSL.js';
import './webgpu/wgsl/color/unpremultiplyWGSL.js';
import './webgpu/wgsl/color/sRGB_to_linear_sRGBWGSL.js';
import './webgpu/wgsl/color/linear_sRGB_to_sRGBWGSL.js';
import './webgpu/wgsl/color/linear_sRGB_to_oklabWGSL.js';
import './webgpu/wgsl/color/oklab_to_linear_sRGBWGSL.js';
import './webgpu/wgsl/color/linear_displayP3_to_linear_sRGBWGSL.js';
import './webgpu/wgsl/color/linear_sRGB_to_linear_displayP3WGSL.js';
import './webgpu/wgsl/color/is_color_in_rangeWGSL.js';
import './webgpu/wgsl/color/gamut_map_linear_sRGBWGSL.js';
import './webgpu/wgsl/color/gamut_map_linear_displayP3WGSL.js';
import './webgpu/wgsl/color/gamut_map_premul_sRGBWGSL.js';
import './webgpu/wgsl/color/gamut_map_premul_displayP3WGSL.js';
import './webgpu/wgsl/color/blend_composeWGSL.js';

// cag/clip
import './webgpu/wgsl/cag/LinearEdgeWGSL.js';
import './webgpu/wgsl/cag/LinearEdgeType.js';
import './webgpu/wgsl/clip/matthes_drakopoulos_clipWGSL.js';
import './webgpu/wgsl/clip/bounds_clip_edgeWGSL.js';

// render-program
import './webgpu/wgsl/render-program/extend_f32WGSL.js';
import './webgpu/wgsl/render-program/extend_i32WGSL.js';
import './webgpu/wgsl/render-program/evaluate_render_program_instructionsWGSL.js';

// "main" modules (a single pipeline each)
import './webgpu/modules/gpu/MainReduceModule.js';
import './webgpu/modules/gpu/MainReduceNonCommutativeModule.js';
import './webgpu/modules/gpu/MainReduceAtomicModule.js';
import './webgpu/modules/gpu/MainScanModule.js';
import './webgpu/modules/gpu/MainRadixHistogramModule.js';
import './webgpu/modules/gpu/MainRadixScatterModule.js';

// "composite" modules
import './webgpu/modules/gpu/ReduceModule.js';
import './webgpu/modules/gpu/ScanModule.js';
import './webgpu/modules/gpu/RadixSortModule.js';
import './webgpu/modules/gpu/MergeSimpleModule.js';
import './webgpu/modules/gpu/MergeModule.js';
import './webgpu/modules/gpu/HistogramModule.js';

// rasterize-two-pass
import './webgpu/wgsl/rasterize-two-pass/TwoPassConfig.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassConfigWGSL.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassConfigType.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassFineRenderableFace.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassFineRenderableFaceWGSL.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassFineRenderableFaceType.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassCoarseRenderableFace.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassCoarseRenderableFaceWGSL.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassCoarseRenderableFaceType.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassInitialRenderableFace.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassInitialRenderableFaceWGSL.js';
import './webgpu/wgsl/rasterize-two-pass/TwoPassInitialRenderableFaceType.js';
import './webgpu/wgsl/rasterize-two-pass/mainTwoPassInitializeAddressesWGSL.js';
import './webgpu/wgsl/rasterize-two-pass/mainTwoPassInitializeAddressesWGSL.js';
import './webgpu/wgsl/rasterize-two-pass/mainTwoPassTileWGSL.js';
import './webgpu/wgsl/rasterize-two-pass/mainTwoPassCoarseWGSL.js';
import './webgpu/wgsl/rasterize-two-pass/mainTwoPassFineWGSL.js';

// rasterize-two-pass modules
import './webgpu/modules/rasterize-two-pass/MainTwoPassFineModule.js';
import './webgpu/modules/rasterize-two-pass/MainTwoPassCoarseModule.js';
import './webgpu/modules/rasterize-two-pass/MainTwoPassTileModule.js';
import './webgpu/modules/rasterize-two-pass/MainTwoPassInitializeAddressesModule.js';
import './webgpu/modules/rasterize-two-pass/TwoPassModule.js';
import './webgpu/modules/rasterize-two-pass/TiledTwoPassModule.js';

import './webgpu/PerformanceTesting.js';
import './webgpu/GPUProfiling.js';
import './webgpu/FaceRasterizer.js';

// testing
import './webgpu/tests/rasterize-two-pass/TwoPassFineSolo.js';
import './webgpu/tests/rasterize-two-pass/TwoPassFineDual.js';
import './webgpu/tests/rasterize-two-pass/TwoPassTiled.js';
import './webgpu/tests/rasterize-two-pass/TwoPassFaceRasterizer.js';

import './webgpu/tests/ShaderTestUtils.js';